### ISSUE TITLE
Rate limit errors when viewing images on remote instances

### ISSUE THREAD

**Issue by chenew** [techy-social/support#1]
Receiving 429 (rate limit) errors while viewing images on the timeline using the web client and Mastodon app. Posts are from remote instances.

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/5931313/220692841-f334e6e2-b15f-4479-9ec8-de64120e117f.png">

**Comment by chenew** [comment]
Default value for media_proxy setting in /home/mastodon/live/config/initializers/rack_attack.rb is 300 requests every 10 minutes.

`throttle('throttle_media_proxy', limit: 30, period: 10.minutes) do |req|`
`  req.throttleable_remote_ip if req.path.start_with?('/media_proxy')`

Considering to modify the rate request limit to a higher value so that it's usable while keeping it low to limit abuse.

**Comment by chenew** [comment]
@stenius I increased the rate limit. Are you seeing any issues now with downloading images?

```
  throttle('throttle_media_proxy', limit: 1_500, period: 5.minutes) do |req|
    req.throttleable_remote_ip if req.path.start_with?('/media_proxy')
  end
```

**Comment by stenius** [comment]
@chenew I haven't seen anything funky yet but I'll keep an eye out for it.

**Comment by stenius** [comment]
looks like my app is still having issues.  The first post I saw was missing
images.  I pulled it up on the website and it loaded there.

**Comment by chenew** [comment]
Do you know approximately what time did happened? I’ll check out the logs.

**Comment by stenius** [comment]
couple minutes before I sent that email.  7:53

**Comment by chenew** [comment]
This issue was related to imagemagick package missing from the Sidekiq servers. Once package was installed, this issue was fixed.
